source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VBAlertController_Example', :exclusive => true do
  pod 'VBAlertController', :path => '../'
end

target 'VBAlertController_Tests', :exclusive => true do
  pod 'VBAlertController', :path => '../'

  
end
